/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package learn;
import java.io.File;
import java.util.ArrayList;
import java.awt.Desktop;
import javax.swing.JOptionPane;
/**
 *
 * @author melaniehendricks
 */
public class edit_GUI extends javax.swing.JFrame {

    /**
     * Creates new form edit_GUI
     */
    public edit_GUI() {
        actArray = new ArrayList<Activity>();
        initComponents();
    }
    
    public edit_GUI(String output){
        this.output = output;
        initComponents();
        actText.setText(output);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        changeBtn = new javax.swing.JButton();
        reprocessBtn = new javax.swing.JButton();
        blah = new javax.swing.JScrollPane();
        errorText = new javax.swing.JTextArea();
        restartBtn = new javax.swing.JButton();
        editDurLabel = new javax.swing.JLabel();
        activityLabel = new javax.swing.JLabel();
        newDurLabel = new javax.swing.JLabel();
        actText = new javax.swing.JTextField();
        newDurText = new javax.swing.JTextField();
        errorLabel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        file = new javax.swing.JMenu();
        exit = new javax.swing.JMenuItem();
        about = new javax.swing.JMenu();
        project = new javax.swing.JMenuItem();
        team = new javax.swing.JMenuItem();
        help = new javax.swing.JMenu();
        tips = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        changeBtn.setText("Change");
        changeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeBtnActionPerformed(evt);
            }
        });

        reprocessBtn.setText("Reprocess");
        reprocessBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reprocessBtnActionPerformed(evt);
            }
        });

        errorText.setColumns(20);
        errorText.setRows(5);
        blah.setViewportView(errorText);

        restartBtn.setText("Restart");
        restartBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restartBtnActionPerformed(evt);
            }
        });

        editDurLabel.setText("Edit Duration:");

        activityLabel.setText("Activity");

        newDurLabel.setText("New Duration");

        actText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actTextActionPerformed(evt);
            }
        });

        newDurText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newDurTextActionPerformed(evt);
            }
        });

        errorLabel.setText("Errors:");

        file.setText("File");

        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        file.add(exit);

        jMenuBar1.add(file);

        about.setText("About");

        project.setText("Project");
        project.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projectActionPerformed(evt);
            }
        });
        about.add(project);

        team.setText("Team");
        team.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teamActionPerformed(evt);
            }
        });
        about.add(team);

        jMenuBar1.add(about);

        help.setText("Help");

        tips.setText("Tips for User");
        tips.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipsActionPerformed(evt);
            }
        });
        help.add(tips);

        jMenuBar1.add(help);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(editDurLabel)
                        .addContainerGap(307, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(actText, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(activityLabel)))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(newDurLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(newDurText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addComponent(changeBtn)
                        .addGap(25, 25, 25))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(reprocessBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(restartBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(blah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(102, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(errorLabel)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(editDurLabel)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(activityLabel)
                        .addGap(18, 18, 18)
                        .addComponent(actText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(changeBtn)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(newDurLabel)
                        .addGap(18, 18, 18)
                        .addComponent(newDurText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addComponent(reprocessBtn)
                .addGap(18, 18, 18)
                .addComponent(errorLabel)
                .addGap(16, 16, 16)
                .addComponent(blah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(restartBtn)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        this.dispose();
        this.setVisible(false);
    }//GEN-LAST:event_exitActionPerformed

    private void restartBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restartBtnActionPerformed
        actText.setText("");
        newDurText.setText("");
        errorText.setText("");
        actArray = new ArrayList<Activity>();
        this.dispose();
        this.setVisible(false);
        network_GUI network = new network_GUI();
        network.setVisible(true);
    }//GEN-LAST:event_restartBtnActionPerformed

    private void reprocessBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reprocessBtnActionPerformed
        Activity[] array = new Activity[actArray.size()];
        array = actArray.toArray(array);
    	NewGraph network = new NewGraph(array);

    	if(network.errorList[0] == 1)
    		errorText.setText(errorText.getText() + "\n" + "Error 3: A node is unconnected.");
    	if(network.errorList[1] == 1)
    		errorText.setText(errorText.getText() + "\n" + "Error 7: The network contains a loop.");
    	String allPaths = "";
        if(network.errorList[0] != 1 && network.errorList[1] != 1){
    		network.InsertionSort(network.paths);
    		allPaths = "";
    		for(int x = network.paths.size() - 1; x > -1; x--){
                        Activity[] arr = new Activity[network.paths.get(x).size()];
                        arr = network.paths.get(x).toArray(arr);
    			allPaths += network.printPath(arr);
    			allPaths += "\n";
    		}
            this.dispose();
            process_GUI second = new process_GUI(allPaths);
            second.setVisible(true);
        }
    }//GEN-LAST:event_reprocessBtnActionPerformed

    private void projectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projectActionPerformed
        project_GUI project = new project_GUI();
        project.setVisible(true);
        this.dispose();
        this.setVisible(false);
    }//GEN-LAST:event_projectActionPerformed

    private void teamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teamActionPerformed
        team_GUI team = new team_GUI();
        team.setVisible(true);
        this.dispose();
        this.setVisible(false);
    }//GEN-LAST:event_teamActionPerformed

    private void tipsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipsActionPerformed
        help_GUI tips = new help_GUI();
        tips.setVisible(true);
        this.dispose();
        this.setVisible(false);
    }//GEN-LAST:event_tipsActionPerformed

    private void actTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_actTextActionPerformed

    private void newDurTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newDurTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newDurTextActionPerformed

    private void changeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeBtnActionPerformed
        
    }//GEN-LAST:event_changeBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(edit_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(edit_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(edit_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(edit_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new edit_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu about;
    private javax.swing.JTextField actText;
    private javax.swing.JLabel activityLabel;
    private javax.swing.JScrollPane blah;
    private javax.swing.JButton changeBtn;
    private javax.swing.JLabel editDurLabel;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JTextArea errorText;
    private javax.swing.JMenuItem exit;
    private javax.swing.JMenu file;
    private javax.swing.JMenu help;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel newDurLabel;
    private javax.swing.JTextField newDurText;
    private javax.swing.JMenuItem project;
    private javax.swing.JButton reprocessBtn;
    private javax.swing.JButton restartBtn;
    private javax.swing.JMenuItem team;
    private javax.swing.JMenuItem tips;
    // End of variables declaration//GEN-END:variables
    private ArrayList<Activity> actArray;
    private String output;
}
